### ISSUE TITLE
Хотелось бы иметь вариант контейнера для разработки

### ISSUE THREAD

**Issue by igormukhin** [notabenoid/notabenoid-dockerfile#1]
Получилось запустить этот контейнер и он отлично работает. Однако также хотелось бы иметь вариант контейнера для разработки, для внесения каких-то изменений в сам код Ноты.

Я не спец по Докеру, но мнится, что тут надо как-то иметь возможность заменять адрес репозитория и убрать depth в:

    RUN     git clone --depth=1 https://github.com/notabenoid/notabenoid.git /srv/$DOMAIN

Тажке, похоже, надо добавить сюда каталог с кодом для его редактирования (и добавить в ридми, как этот вольюм подключать):

    VOLUME  ["/etc", "/var/log", "/var/lib/postgresql"]

Может, еще чего-то надо. Не спец, не знаю. Просто хотел пару мелочей в Ноте поправить.

Возможно, также нужно сразу создать пару тестовых пользователей.

**Comment by igormukhin** [comment]
Либо же, насколько я понимаю, было бы правильней, чтобы код лежал не в контейнере, а внешне, и подключался к контейнеру через внешний volume.
Мысли вслух: Но тогда база не создастся до старта контейнера. Может встроить создание базы в первый вызов первой страницы Ноты? Так в Joomla сделано.
Либо может поможет разделить контейнеры на notabenoid-db и notabenoid-www.

**Comment by opennota** [comment]
Я прокидываю код в этот же контейнер из внешней директории, используя `-v`, и правлю его извне. Потребовалось только проставить права доступа, чтобы процессы, запущенные в контейнере, тоже имели к нему доступ.

**Comment by igormukhin** [comment]
Да, если вы добавить в README описание того, как это делается, это я думаю решило бы задачу.

Кстати, по-моему, в Нотке есть возможность загружать какие-то картинки. Каталог, в который они загружаются, надо, похоже, тоже в VOLUME добавить.
